// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

crate::windows_link::link!("kernel32.dll" "system" fn ExitProcess(uexitcode : u32) -> !);
pub const DLL_PROCESS_ATTACH: u32 = 1u32;
pub const DLL_PROCESS_DETACH: u32 = 0u32;
pub type HANDLE = *mut core::ffi::c_void;
pub type PIMAGE_TLS_CALLBACK = Option<
    unsafe extern "system" fn(
        dllhandle: *mut core::ffi::c_void,
        reason: u32,
        reserved: *mut core::ffi::c_void,
    ),
>;
